[tool.poetry]
name = "protosend"
version = "0.0.0"
description = ""
authors = ["Jesmigel A. Cantos <jesmigel.developer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
nptyping = "^2.5.0"
pytest = "^6.2"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
