dynamic_vars:
  stage: build
  before_script:
    - printenv | grep BRANCH
  script:
    - echo "PST_SEND_OCI_TAG=$(grep -m 1 -o '[0-9].*' .release)-dev.c${CI_COMMIT_SHORT_SHA}" > build.env
    - echo "PST_SEND_OCI_RELEASE=$(grep -m 1 -o '[0-9].*' .release)" > build.env
  artifacts:
    reports:
      dotenv: build.env

oci-image-build:
  needs:
    - dynamic_vars
  dependencies:
    - dynamic_vars
  script:
    make oci-build-all OCI_IMAGES="${OCI_IMAGES}" CAR_OCI_REGISTRY_HOST=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME} OCI_BUILD_ADDITIONAL_ARGS=" --build-arg SEND_BASE_IMAGE=${SEND_BASE_IMAGE} --build-arg SEND_BUILDER=${PST_OCI_SEND_BUILDER} --build-arg SEND_RUNTIME=${PST_SEND_OCI_RUNTIME}"

oci-image-publish:
  when: manual